import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="flex flex-col pt-[30px] px-[20px] lg:container lg:mx-auto lg:px-16">
          <Navbar />
          {children}
        </main>
        <main className="lg:mx-auto lg:container lg:px-[50px]">
          <Footer />
        </main>
      </body>
    </html>
  );
}
